# Generated by Django 4.2.23 on 2025-07-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_comment_user_project_user_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
